version: "3.7"
services:
  client:
    image: economics:client
    container_name: client
    networks:
      economics: {}
    ports:
      - "3000:80"
  eureka:
    image: economics:server-eureka
    container_name: eureka
    networks:
      economics: {}
    ports:
      - "8761:8761"
  warehouses:
    image: economics:server-warehouses
    container_name: warehouses
    networks:
      economics: {}
    ports:
      - "8001:8001"
  products:
    image: economics:server-products
    container_name: products
    networks:
      economics: {}
    ports:
      - "8100:8100"
    depends_on:
      - database
    restart: always
  database:
    image: economics:database
    container_name: database
    networks:
      economics: {}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://database:5432"]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  economics:
    external: true
    name: economics
# sudo docker network create economics --subnet 172.24.24.0/24