version: "3.7"
services:
  client:
    image: economics:client
    container_name: client
    networks:
      - economics
    ports:
      - "3000:80"
  reverse-proxy:
    image: economics:reverse-proxy
    container_name: reverse-proxy
    networks:
      - economics
    ports:
      - "2000:80"
    volumes:
      - "./reverse-proxy/config:/etc/nginx:ro"
    restart: on-failure
  eureka:
    image: economics:server-eureka
    container_name: eureka
    networks:
      - economics
    ports:
      - "8761:8761"
  warehouses:
    image: economics:server-warehouses
    container_name: warehouses
    env_file:
      env/warehouses.env
    networks:
      - economics
    ports:
      - "8001:8001"
    depends_on:
      - database
      - eureka
    restart: on-failure
  products:
    image: economics:server-products
    container_name: products
    env_file:
      env/products.env
    networks:
      - economics
    ports:
      - "8100:8100"
    depends_on:
      - database
    restart: on-failure
  database:
    image: economics:database
    env_file:
      env/database.env
    container_name: database
    networks:
      - economics
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
networks:
  economics:
    external:
      name: economics
volumes:
  database:
    external: true
    name: economics-database-volume