version: "3.7"
services:
  client:
    image: economics:client
    container_name: client
    networks:
      - economics
    ports:
      - "3000:80"
  eureka:
    image: economics:server-eureka
    container_name: eureka
    networks:
      - economics
    ports:
      - "8761:8761"
  warehouses:
    image: economics:server-warehouses
    container_name: warehouses
    env_file:
      env/warehouses.env
    networks:
      - economics
    ports:
      - "8001:8001"
  products:
    image: economics:server-products
    container_name: products
    env_file:
      env/products.env
    networks:
      - economics
    ports:
      - "8100:8100"
    depends_on:
      - database
    restart: on-failure
  database:
    image: economics:database
    env_file:
      env/database.env
    container_name: database
    networks:
      - economics
    ports:
      - "5432:5432"
networks:
  economics:
    external:
      name: economics