version: "3.7"
services:
  client:
    image: economics:client
    networks:
      economics: {}
    ports:
      - "80:80"
  eureka:
    image: economics:server-eureka
    networks:
      economics: {}
    ports:
      - "8761:8761"
  warehouses:
    image: economics:server-warehouses
    networks:
      economics: {}
    ports:
      - "8001:8001"
  products:
    image: economics:server-products
    networks:
      economics: {}
    ports:
      - "8100:8100"
    depends_on:
      - database
  database:
    image: economics:database
    networks:
      economics: {}
    ports:
      - "5432:5432"
networks:
  economics:
    external: true
    name: economics
# sudo docker network create economics --subnet 172.24.24.0/24